# Generated by Django 4.2.16 on 2025-10-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsandevents_summary_es_newsandevents_summary_fr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_en",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_es",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_fr",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_ru",
        ),
    ]
