# Generated by Django 4.2.16 on 2025-10-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_videoprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["module", "title"],
                "verbose_name": "Bootcamp Course",
                "verbose_name_plural": "Bootcamp Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["title"],
                "verbose_name": "Bootcamp Program",
                "verbose_name_plural": "Bootcamp Programs",
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_elective",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.AddField(
            model_name="course",
            name="duration_weeks",
            field=models.IntegerField(
                choices=[
                    (4, "4 Weeks - Quick Start"),
                    (8, "8 Weeks - Standard"),
                    (12, "12 Weeks - Comprehensive"),
                    (16, "16 Weeks - In-Depth"),
                    (24, "24 Weeks - Master Program"),
                ],
                default=8,
                help_text="Bootcamp duration in weeks",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_premium",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is this a premium/paid course?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="module",
            field=models.CharField(
                choices=[
                    ("Module 1", "Module 1 - Introduction"),
                    ("Module 2", "Module 2 - Fundamentals"),
                    ("Module 3", "Module 3 - Intermediate"),
                    ("Module 4", "Module 4 - Advanced"),
                    ("Module 5", "Module 5 - Capstone Project"),
                ],
                default="Module 1",
                help_text="Which module this course belongs to",
                max_length=200,
                verbose_name="Bootcamp Module",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show this bootcamp on homepage featured section",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner - New to technology"),
                    ("Intermediate", "Intermediate - Some experience"),
                    ("Advanced", "Advanced - Strong knowledge"),
                    ("Expert", "Expert - Industry professional"),
                ],
                default="Beginner",
                help_text="Recommended skill level for this bootcamp",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="total_duration_weeks",
            field=models.IntegerField(
                default=12, help_text="Total bootcamp duration in weeks"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="Unique course code (e.g., 'AI101')",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner - New to technology"),
                    ("Intermediate", "Intermediate - Some experience"),
                    ("Advanced", "Advanced - Strong knowledge"),
                    ("Expert", "Expert - Industry professional"),
                ],
                help_text="Required experience level for participants",
                max_length=25,
                null=True,
                verbose_name="Experience Level",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                help_text="The bootcamp program this course belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="course.program",
                verbose_name="Bootcamp Program",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Brief course description for participants",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_en",
            field=models.TextField(
                blank=True,
                help_text="Brief course description for participants",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_es",
            field=models.TextField(
                blank=True,
                help_text="Brief course description for participants",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_fr",
            field=models.TextField(
                blank=True,
                help_text="Brief course description for participants",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_ru",
            field=models.TextField(
                blank=True,
                help_text="Brief course description for participants",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Course title (e.g., 'Introduction to Machine Learning')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_en",
            field=models.CharField(
                help_text="Course title (e.g., 'Introduction to Machine Learning')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_es",
            field=models.CharField(
                help_text="Course title (e.g., 'Introduction to Machine Learning')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_fr",
            field=models.CharField(
                help_text="Course title (e.g., 'Introduction to Machine Learning')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_ru",
            field=models.CharField(
                help_text="Course title (e.g., 'Introduction to Machine Learning')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what participants will learn",
                null=True,
                verbose_name="Bootcamp Description",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="summary_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what participants will learn",
                null=True,
                verbose_name="Bootcamp Description",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="summary_es",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what participants will learn",
                null=True,
                verbose_name="Bootcamp Description",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="summary_fr",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what participants will learn",
                null=True,
                verbose_name="Bootcamp Description",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="summary_ru",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what participants will learn",
                null=True,
                verbose_name="Bootcamp Description",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title",
            field=models.CharField(
                help_text="Name of the bootcamp program (e.g., 'AI & Machine Learning Bootcamp')",
                max_length=150,
                unique=True,
                verbose_name="Bootcamp Name",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title_en",
            field=models.CharField(
                help_text="Name of the bootcamp program (e.g., 'AI & Machine Learning Bootcamp')",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Bootcamp Name",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title_es",
            field=models.CharField(
                help_text="Name of the bootcamp program (e.g., 'AI & Machine Learning Bootcamp')",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Bootcamp Name",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title_fr",
            field=models.CharField(
                help_text="Name of the bootcamp program (e.g., 'AI & Machine Learning Bootcamp')",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Bootcamp Name",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title_ru",
            field=models.CharField(
                help_text="Name of the bootcamp program (e.g., 'AI & Machine Learning Bootcamp')",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Bootcamp Name",
            ),
        ),
    ]
