# Generated by Django 4.2.16 on 2025-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_alter_course_options_alter_program_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["title"],
                "verbose_name": "Bootcamp Course",
                "verbose_name_plural": "Bootcamp Courses",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="credit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_elective",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration_weeks",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (4, "4 Weeks - Quick Start"),
                    (8, "8 Weeks - Standard"),
                    (12, "12 Weeks - Comprehensive"),
                    (16, "16 Weeks - In-Depth"),
                    (24, "24 Weeks - Master Program"),
                ],
                default=8,
                help_text="Bootcamp duration in weeks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beginner", "Beginner - New to technology"),
                    ("Intermediate", "Intermediate - Some experience"),
                    ("Advanced", "Advanced - Strong knowledge"),
                    ("Expert", "Expert - Industry professional"),
                ],
                help_text="Required experience level for participants",
                max_length=25,
                null=True,
                verbose_name="Experience Level",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Module 1", "Module 1 - Introduction"),
                    ("Module 2", "Module 2 - Fundamentals"),
                    ("Module 3", "Module 3 - Intermediate"),
                    ("Module 4", "Module 4 - Advanced"),
                    ("Module 5", "Module 5 - Capstone Project"),
                ],
                default="Module 1",
                help_text="Which module this course belongs to",
                max_length=200,
                null=True,
                verbose_name="Bootcamp Module",
            ),
        ),
    ]
