# Generated by Django 5.2.7 on 2025-11-03 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_remove_course_summary_en_remove_course_summary_es_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoDRMLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("access", "Video Access"),
                            ("violation", "DRM Violation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("screen_recording", "Screen Recording Detected"),
                            ("devtools_open", "Developer Tools Opened"),
                            ("right_click", "Right-Click Attempt"),
                            ("keyboard_shortcut", "Keyboard Shortcut Blocked"),
                            ("video_tampering", "Video Source Tampering"),
                            ("download_attempt", "Download Attempt"),
                            ("inspect_element", "Inspect Element Attempt"),
                            ("other", "Other Violation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("screen_resolution", models.CharField(blank=True, max_length=50)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drm_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drm_logs",
                        to="course.uploadvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="course_vide_timesta_eda557_idx"
                    ),
                    models.Index(
                        fields=["log_type", "-timestamp"],
                        name="course_vide_log_typ_7fd780_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="course_vide_user_id_862270_idx",
                    ),
                ],
            },
        ),
    ]
