# Generated by Django 4.2.16 on 2025-10-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_question_content_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choice_en",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_es",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_fr",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_ru",
        ),
    ]
