# Generated by Django 4.2.16 on 2025-10-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_course_options_course_credit_and_more"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ("-student__date_joined",),
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner - New to the technology"),
                    ("Intermediate", "Intermediate - Some experience"),
                    ("Advanced", "Advanced - Strong knowledge"),
                    ("Expert", "Expert - Industry professional"),
                ],
                help_text="Your current experience level with technology",
                max_length=25,
                null=True,
                verbose_name="Experience Level",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                help_text="Select the bootcamp or masterclass you want to join",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.program",
                verbose_name="Bootcamp/Masterclass",
            ),
        ),
    ]
